#! /bin/sh
### BEGIN INIT INFO
# Provides: svnserve
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: SVN initscript
# Description: This file starts the SVN server (svnserve) at boot and should be
# placed in /etc/init.d.
### END INIT INFO

# Author: Sean O’Brien

# Do NOT “set -e”

# PATH should only include /usr/* if it runs after the mountnfs.sh script
test -f /usr/bin/svnserve || exit 0

OPTIONS='-d -r /opt/SVN'

case $1 in
start)
echo -n "Starting subversion daemon:"
echo -n " svnserve"
start-stop-daemon -S --quiet --oknodo --exec /usr/bin/svnserve -- -d --listen-port=4000 -r /opt/SVN
echo "."
;;
stop)
echo -n "Stopping subversion daemon:"
echo -n " svnserve"
start-stop-daemon --stop --quiet --oknodo --exec /usr/bin/svnserve
echo "."
;;
reload)
;;
force-reload)
$0 restart
;;
restart)
$0 stop
$0 start
;;
*)
echo "Usage: /etc/init.d/subversion {start|stop|reload|restart}"
exit 1
;;
esac

exit 0
